### ISSUE TITLE
fix for the nav

### ISSUE THREAD

**Issue by Haroenv** [bullgit/bullgit.github.io#25]
```css
.site--navigation .nav--list-item {
    display: inline-block;
    margin-left: 1.4em;
}
```

instead of:

```css
.site--navigation .nav--list-item {
    display: inline-block;
    margin-left: 2.5em;
}
```
